FROM node:24-alpine
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

COPY package.json pnpm-lock.yaml nest-cli.json tsconfig.json tsconfig.build.json ./
COPY apps ./apps
COPY libs ./libs
RUN pnpm install --frozen-lockfile

CMD ["pnpm", "exec", "nest", "start", "wikimedia-streams-microservice", "--watch"]
